name: test wiki init

on:
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@users.noreply.github.com
  GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH: master

  
jobs:
  init-config:
    runs-on: [ubuntu-latest]
    steps:
      - name: init repo
        run: |
          function debug() {
              echo "::debug file=${BASH_SOURCE[0]},line=${BASH_LINENO[0]}::$1"
          }

          function warning() {
              echo "::warning file=${BASH_SOURCE[0]},line=${BASH_LINENO[0]}::$1"
          }

          function error() {
              echo "::error file=${BASH_SOURCE[0]},line=${BASH_LINENO[0]}::$1"
          }

          function add_mask() {
              echo "::add-mask::$1"
          }
          ###############################################################################
          ## Check required inputs that don't have defaults
          ###############################################################################

          if [ -z "$GITHUB_PERSONAL_ACCESS_TOKEN" ]; then
            error "GITHUB_PERSONAL_ACCESS_TOKEN environment variable is not set"
            exit 1
          fi

          add_mask "${GITHUB_PERSONAL_ACCESS_TOKEN}"

          ###############################################################################
          ## Check optional inputs that don't have defaults
          ###############################################################################
          if [ -z "${GIT_AUTHOR_EMAIL:-}" ]; then
              debug "GIT_AUTHOR_EMAIL not set, using default"
              GIT_AUTHOR_EMAIL="$GIT_AUTHOR_NAME@users.noreply.github.com"
          fi

          ###############################################################################
          ## Set wiki repo URL
          ###############################################################################
          if [ -z "$GITHUB_REPOSITORY" ]; then
              error "GITHUB_REPOSITORY environment variable is not set"
              exit 1
          fi
          GIT_REPOSITORY_URL="https://${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/$GITHUB_REPOSITORY.wiki.git"


          ###############################################################################
          ## Check out wiki
          ###############################################################################
          debug "Checking out wiki repository"
          tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
          (
            cd "$tmp_dir" || exit 1
            echo "# Hello world" >> Home.md
            git init
            git config user.name "$GIT_AUTHOR_NAME"
            git config user.email "$GIT_AUTHOR_EMAIL"
            git config init.defaultBranch master
            echo "$GIT_REPOSITORY_URL"
            git pull "$GIT_REPOSITORY_URL"
            
            git branch -m master 
            git add Home.md
            git commit -m "chore(docs): Initial commit for repo"
            git push -u origin master
          )
          
          #git remote add origin git@github.com:mistereechapman/test.app.wiki.git
          #git remote add origin ${GIT_REPOSITORY_URL}
          #git remote add origin git@github.com:mistereechapman/test.app.wiki.git
          
        shell: bash
