name: test wiki init

on:
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com
  
jobs:
  init-config:
    runs-on: [ubuntu-latest]
    steps:
      - name: init repo
        run: |
          echo "# Hello world" >> Home.md
          git init
          git config --global user.email "${{ ENV.GIT_AUTHOR_EMAIL }}"
          git config --global user.name "${{ ENV.GIT_AUTHOR_NAME }}"
          git config --global init.defaultBranch master
          git add Home.md
          git commit -m "Initial commit for repo"
          git branch -m master          
          git remote add origin git@github.com:mistereechapman/test.app.wiki.git
          git push -u origin master
        shell: bash
